"""
Dataset loading utilities.

Loads pre-processed patient parquet files generated by generate_demo_data.py
(or extracted from MIMIC-III using the extraction scripts).
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from pathlib import Path
from typing import List, Tuple


def load_split(
    data_dir: str,
    split: str,
) -> Tuple[List[pd.DataFrame], np.ndarray, pd.DataFrame]:
    """
    Load a dataset split (train / val / test).

    Returns
    -------
    series_list : list of DataFrames, one per patient
    labels      : 1-D int array of binary sepsis labels
    meta        : DataFrame with patient metadata
    """
    base = Path(data_dir) / split
    meta_path   = Path(data_dir) / f"{split}_meta.csv"
    labels_path = Path(data_dir) / f"{split}_labels.npy"

    if not base.exists():
        raise FileNotFoundError(
            f"Split directory not found: {base}\n"
            "Run `python src/data/generate_demo_data.py` first."
        )

    meta   = pd.read_csv(meta_path)
    labels = np.load(labels_path)

    series_list = []
    for pid in meta["patient_id"]:
        parquet_file = base / f"{pid}.parquet"
        df = pd.read_parquet(parquet_file)
        series_list.append(df)

    return series_list, labels, meta
